"""add external reservations

Revision ID: 434495e63959
Revises: 7c531df121e9
Create Date: 2026-01-15 23:40:09.260504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434495e63959'
down_revision = '7c531df121e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('external_uid', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_reservation_cancel_token'), ['cancel_token'], unique=True)
        batch_op.create_unique_constraint('uq_reservation_external_uid',['external_uid'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reservation_external_uid',type_='unique')
        batch_op.drop_index(batch_op.f('ix_reservation_cancel_token'))
        batch_op.drop_column('external_uid')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
