"""Add WhatsApp contact fields to Apartment

Revision ID: 5206a529e7d0
Revises: 8008a2a65769
Create Date: 2026-07-28 12:14:45.862466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5206a529e7d0'
down_revision = '8008a2a65769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=30), nullable=True, comment='WhatsApp number in international format (e.g., 393000000000)'))
        batch_op.add_column(sa.Column('whatsapp_default_message', sa.Text(), nullable=True, comment='Default pre-filled message for WhatsApp'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_default_message')
        batch_op.drop_column('whatsapp_number')

    # ### end Alembic commands ###
