"""Add trust badges and review platform fields to Apartment

Revision ID: 525c32a2d465
Revises: 5206a529e7d0
Create Date: 2026-07-28 12:22:38.775793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525c32a2d465'
down_revision = '5206a529e7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_review_score', sa.Float(), nullable=True, comment='Booking.com review score (0-10)'))
        batch_op.add_column(sa.Column('booking_review_count', sa.Integer(), nullable=True, comment='Booking.com number of reviews'))
        batch_op.add_column(sa.Column('booking_property_id', sa.String(length=50), nullable=True, comment='Booking.com property ID for widget'))
        batch_op.add_column(sa.Column('airbnb_review_score', sa.Float(), nullable=True, comment='Airbnb review score (0-5)'))
        batch_op.add_column(sa.Column('airbnb_review_count', sa.Integer(), nullable=True, comment='Airbnb number of reviews'))
        batch_op.add_column(sa.Column('airbnb_listing_id', sa.String(length=50), nullable=True, comment='Airbnb listing ID'))
        batch_op.add_column(sa.Column('google_review_score', sa.Float(), nullable=True, comment='Google reviews score (0-5)'))
        batch_op.add_column(sa.Column('google_review_count', sa.Integer(), nullable=True, comment='Google reviews count'))
        batch_op.add_column(sa.Column('google_place_id', sa.String(length=100), nullable=True, comment='Google Places ID'))
        batch_op.add_column(sa.Column('tripadvisor_review_score', sa.Float(), nullable=True, comment='TripAdvisor score (0-5)'))
        batch_op.add_column(sa.Column('tripadvisor_review_count', sa.Integer(), nullable=True, comment='TripAdvisor review count'))
        batch_op.add_column(sa.Column('tripadvisor_location_id', sa.String(length=50), nullable=True, comment='TripAdvisor location ID'))
        batch_op.add_column(sa.Column('vrbo_review_score', sa.Float(), nullable=True, comment='VRBO/HomeAway score (0-5)'))
        batch_op.add_column(sa.Column('vrbo_review_count', sa.Integer(), nullable=True, comment='VRBO review count'))
        batch_op.add_column(sa.Column('vrbo_listing_id', sa.String(length=50), nullable=True, comment='VRBO listing ID'))
        batch_op.add_column(sa.Column('stripe_verified', sa.Boolean(), nullable=True, comment='Show Stripe verified badge'))
        batch_op.add_column(sa.Column('ssl_certified', sa.Boolean(), nullable=True, comment='Show SSL/Secure badge'))
        batch_op.add_column(sa.Column('gdpr_compliant', sa.Boolean(), nullable=True, comment='Show GDPR compliant badge'))
        batch_op.add_column(sa.Column('pci_compliant', sa.Boolean(), nullable=True, comment='Show PCI DSS compliant badge'))
        batch_op.add_column(sa.Column('custom_badge_1_image', sa.String(length=200), nullable=True, comment='Custom badge 1 image filename'))
        batch_op.add_column(sa.Column('custom_badge_1_link', sa.String(length=300), nullable=True, comment='Custom badge 1 link URL'))
        batch_op.add_column(sa.Column('custom_badge_1_alt', sa.String(length=100), nullable=True, comment='Custom badge 1 alt text'))
        batch_op.add_column(sa.Column('custom_badge_2_image', sa.String(length=200), nullable=True, comment='Custom badge 2 image filename'))
        batch_op.add_column(sa.Column('custom_badge_2_link', sa.String(length=300), nullable=True, comment='Custom badge 2 link URL'))
        batch_op.add_column(sa.Column('custom_badge_2_alt', sa.String(length=100), nullable=True, comment='Custom badge 2 alt text'))
        batch_op.add_column(sa.Column('custom_badge_3_image', sa.String(length=200), nullable=True, comment='Custom badge 3 image filename'))
        batch_op.add_column(sa.Column('custom_badge_3_link', sa.String(length=300), nullable=True, comment='Custom badge 3 link URL'))
        batch_op.add_column(sa.Column('custom_badge_3_alt', sa.String(length=100), nullable=True, comment='Custom badge 3 alt text'))
        batch_op.add_column(sa.Column('show_reviews_in_footer', sa.Boolean(), nullable=True, comment='Show review badges in footer'))
        batch_op.add_column(sa.Column('show_reviews_on_homepage', sa.Boolean(), nullable=True, comment='Show review badges on homepage'))
        batch_op.add_column(sa.Column('show_reviews_on_booking', sa.Boolean(), nullable=True, comment='Show review badges on booking page'))
        batch_op.add_column(sa.Column('show_payment_badges_in_footer', sa.Boolean(), nullable=True, comment='Show payment badges in footer'))
        batch_op.add_column(sa.Column('show_payment_badges_on_checkout', sa.Boolean(), nullable=True, comment='Show payment badges on checkout'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.drop_column('show_payment_badges_on_checkout')
        batch_op.drop_column('show_payment_badges_in_footer')
        batch_op.drop_column('show_reviews_on_booking')
        batch_op.drop_column('show_reviews_on_homepage')
        batch_op.drop_column('show_reviews_in_footer')
        batch_op.drop_column('custom_badge_3_alt')
        batch_op.drop_column('custom_badge_3_link')
        batch_op.drop_column('custom_badge_3_image')
        batch_op.drop_column('custom_badge_2_alt')
        batch_op.drop_column('custom_badge_2_link')
        batch_op.drop_column('custom_badge_2_image')
        batch_op.drop_column('custom_badge_1_alt')
        batch_op.drop_column('custom_badge_1_link')
        batch_op.drop_column('custom_badge_1_image')
        batch_op.drop_column('pci_compliant')
        batch_op.drop_column('gdpr_compliant')
        batch_op.drop_column('ssl_certified')
        batch_op.drop_column('stripe_verified')
        batch_op.drop_column('vrbo_listing_id')
        batch_op.drop_column('vrbo_review_count')
        batch_op.drop_column('vrbo_review_score')
        batch_op.drop_column('tripadvisor_location_id')
        batch_op.drop_column('tripadvisor_review_count')
        batch_op.drop_column('tripadvisor_review_score')
        batch_op.drop_column('google_place_id')
        batch_op.drop_column('google_review_count')
        batch_op.drop_column('google_review_score')
        batch_op.drop_column('airbnb_listing_id')
        batch_op.drop_column('airbnb_review_count')
        batch_op.drop_column('airbnb_review_score')
        batch_op.drop_column('booking_property_id')
        batch_op.drop_column('booking_review_count')
        batch_op.drop_column('booking_review_score')

    # ### end Alembic commands ###
