"""initial clean setup with payment fields

Revision ID: 5bc27843317a
Revises: 
Create Date: 2026-06-23 11:00:58.400562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc27843317a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_per_night', sa.Float(), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('i_cal_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('guest_email', sa.String(length=120), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('num_guests', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_token', sa.String(length=128), nullable=True),
    sa.Column('external_uid', sa.String(length=128), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=128), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'cancelled')", name='ck_reservation_status'),
    sa.CheckConstraint('check_out > check_in', name='ck_dates_valid'),
    sa.CheckConstraint('num_guests >= 1 AND num_guests <= 4', name='ck_guests_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cancel_token', name='uq_reservation_cancel_token'),
    sa.UniqueConstraint('external_uid', name='uq_reservation_external_uid')
    )
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_cancel_token'), ['cancel_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_reservation_external_uid'), ['external_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_reservation_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_stripe_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_external_uid'))
        batch_op.drop_index(batch_op.f('ix_reservation_cancel_token'))

    op.drop_table('reservation')
    op.drop_table('i_cal_feed')
    op.drop_table('apartment')
    # ### end Alembic commands ###
