"""empty message

Revision ID: 67de48ab50a7
Revises: e3803d98d829
Create Date: 2026-01-24 19:22:21.434712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67de48ab50a7'
down_revision = 'e3803d98d829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('cancel_token',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_reservation_external_uid', ['external_uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reservation_external_uid', type_='unique')
        batch_op.alter_column('cancel_token',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
