"""add italian compliance fields to apartment

Revision ID: 67ea69c74893
Revises: 771f86e69e3f
Create Date: 2026-07-27 16:21:00.236032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ea69c74893'
down_revision = '771f86e69e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.alter_column('tourist_tax_category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('tourist_tax_rate',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('max_guests',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('questura_ip_whitelisted',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Boolean(),
               existing_nullable=True)

    with op.batch_alter_table('compliance_config', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_compliance_config_key'), ['key'], unique=True)

    with op.batch_alter_table('questura_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_questura_log_reservation_id'), ['reservation_id'], unique=False)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('checkin_completed_at',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('checkin_token_used',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_reservation_checkin_token'), ['checkin_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_checkin_token'))
        batch_op.alter_column('checkin_token_used',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('checkin_completed_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('questura_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questura_log_reservation_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('compliance_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_config_key'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.alter_column('questura_ip_whitelisted',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('max_guests',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('tourist_tax_rate',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('tourist_tax_category',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
