"""add cancellation

Revision ID: 7c531df121e9
Revises: b3cb2ea87760
Create Date: 2026-01-15 22:55:42.253170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c531df121e9'
down_revision = 'b3cb2ea87760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(
            'uq_reservation_cancel_token',
            ['cancel_token']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cancel_token')

    # ### end Alembic commands ###
