"""add stripe_payment_intent_id to reservation

Revision ID: 7e9f56c03aba
Revises: 67de48ab50a7
Create Date: 2026-05-07 18:48:40.838478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9f56c03aba'
down_revision = '67de48ab50a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.String(length=128), nullable=True))
        batch_op.alter_column('guest_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_reservation_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_stripe_payment_intent_id'))
        batch_op.alter_column('guest_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('stripe_payment_intent_id')

    # ### end Alembic commands ###
