"""Add smart access (Shelly gate + Nuki door) configuration and access tokens

Revision ID: 8008a2a65769
Revises: 20260727_add_questura_fields
Create Date: 2026-07-28 10:46:06.187562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8008a2a65769'
down_revision = '20260727_add_questura_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelly_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shelly_host', sa.String(length=100), nullable=True, comment='Shelly IP or hostname (e.g., 192.168.1.50 or shelly-gate.local)'))
        batch_op.add_column(sa.Column('shelly_auth_key', sa.String(length=100), nullable=True, comment='Shelly Gen4 auth key (if auth enabled)'))
        batch_op.add_column(sa.Column('shelly_relay_channel', sa.Integer(), nullable=True, comment='Relay channel (0 for Shelly 1 Mini)'))
        batch_op.add_column(sa.Column('shelly_pulse_duration', sa.Integer(), nullable=True, comment='Gate pulse duration in seconds'))
        batch_op.add_column(sa.Column('nuki_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('nuki_smartlock_id', sa.String(length=50), nullable=True, comment='Nuki Smart Lock ID (decimal)'))
        batch_op.add_column(sa.Column('nuki_web_token', sa.String(length=200), nullable=True, comment='Nuki Web API token (Bearer)'))
        batch_op.add_column(sa.Column('nuki_web_base_url', sa.String(length=100), nullable=True, comment='Nuki Web API base URL'))
        batch_op.add_column(sa.Column('nuki_unlock_action', sa.String(length=20), nullable=True, comment='unlock or unlatch (open door)'))

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('access_token_created', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reservation_access_token'), ['access_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_access_token'))
        batch_op.drop_column('access_token_created')
        batch_op.drop_column('access_token')

    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.drop_column('nuki_unlock_action')
        batch_op.drop_column('nuki_web_base_url')
        batch_op.drop_column('nuki_web_token')
        batch_op.drop_column('nuki_smartlock_id')
        batch_op.drop_column('nuki_enabled')
        batch_op.drop_column('shelly_pulse_duration')
        batch_op.drop_column('shelly_relay_channel')
        batch_op.drop_column('shelly_auth_key')
        batch_op.drop_column('shelly_host')
        batch_op.drop_column('shelly_enabled')

    # ### end Alembic commands ###
