"""add nuki keypad code fields to reservation

Revision ID: c0ffee123456
Revises: f7a8b9c0d1e2
Create Date: 2026-08-06 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ffee123456'
down_revision = 'f7a8b9c0d1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keypad_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('keypad_auth_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('keypad_created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('keypad_created_at')
        batch_op.drop_column('keypad_auth_id')
        batch_op.drop_column('keypad_code')

    # ### end Alembic commands ###
