"""Add widget embed fields to Apartment

Revision ID: c99797619e6f
Revises: 525c32a2d465
Create Date: 2026-07-28 14:31:51.562870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99797619e6f'
down_revision = '525c32a2d465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_widget_js', sa.Text(), nullable=True, comment='Booking.com official widget embed JS'))
        batch_op.add_column(sa.Column('airbnb_widget_js', sa.Text(), nullable=True, comment='Airbnb official widget embed JS'))
        batch_op.add_column(sa.Column('google_widget_js', sa.Text(), nullable=True, comment='Google Reviews widget embed JS'))
        batch_op.add_column(sa.Column('trustpilot_widget_js', sa.Text(), nullable=True, comment='Trustpilot widget embed JS'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.drop_column('trustpilot_widget_js')
        batch_op.drop_column('google_widget_js')
        batch_op.drop_column('airbnb_widget_js')
        batch_op.drop_column('booking_widget_js')

    # ### end Alembic commands ###
