"""add guest wifi fields to apartment

Revision ID: d3a5f2b1c4e9
Revises: b3c4d5e6f7a8
Create Date: 2026-08-11 12:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd3a5f2b1c4e9'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wifi_ssid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wifi_password', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wifi_security', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('wifi_band', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('wifi_hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.drop_column('wifi_hidden')
        batch_op.drop_column('wifi_band')
        batch_op.drop_column('wifi_security')
        batch_op.drop_column('wifi_password')
        batch_op.drop_column('wifi_ssid')

    # ### end Alembic commands ###
