"""limit guests 1 to 4

Revision ID: e3803d98d829
Revises: 434495e63959
Create Date: 2026-01-15 23:47:09.414050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3803d98d829'
down_revision = '434495e63959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('external_uid',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_reservation_external_uid'), type_='unique')
        batch_op.create_index(batch_op.f('ix_reservation_external_uid'), ['external_uid'], unique=True)
        batch_op.create_unique_constraint('uq_reservation_cancel_token', ['cancel_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reservation_cancel_token', type_='unique')
        batch_op.drop_index(batch_op.f('ix_reservation_external_uid'))
        batch_op.create_unique_constraint(batch_op.f('uq_reservation_external_uid'), ['external_uid'])
        batch_op.alter_column('external_uid',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
