"""add cleaning access

Revision ID: f5dfcb91edf1
Revises: e9f8a7b6c5d4
Create Date: 2026-08-19 10:17:01.282640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5dfcb91edf1'
down_revision = 'e9f8a7b6c5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False, comment='Short name, e.g. Cleaning 24/08'),
    sa.Column('message', sa.Text(), nullable=True, comment='Message shown on the share link'),
    sa.Column('starts_at', sa.DateTime(), nullable=True, comment='Access window start (Europe/Rome naive)'),
    sa.Column('ends_at', sa.DateTime(), nullable=True, comment='Access window end (Europe/Rome naive)'),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True, comment='Link responds; inactive links show disabled state'),
    sa.Column('auto_generated', sa.Boolean(), nullable=True, comment='Prefilled from a reservation gap'),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('keypad_code', sa.String(length=6), nullable=True),
    sa.Column('keypad_auth_id', sa.String(length=64), nullable=True),
    sa.Column('keypad_created_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cleaning_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cleaning_access_token'), ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleaning_access_token'))

    op.drop_table('cleaning_access')
    # ### end Alembic commands ###
